### ISSUE TITLE
 'Call to undefined method [package]

### ISSUE THREAD

**Issue by renege** [JeffreyWay/Laravel-4-Generators#449]
Laravel 5 with "way/generators": "~3.0"

```
vagrant@homestead:~/Code/site$ php artisan generate
exception 'BadMethodCallException' with message 'Call to undefined method [package]' in /home/vagrant/Code/site/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php:226
Stack trace:
#0 /home/vagrant/Code/site/vendor/way/generators/src/Way/Generators/GeneratorsServiceProvider.php(28): Illuminate\Support\ServiceProvider->__call('package', Array)
#1 /home/vagrant/Code/site/vendor/way/generators/src/Way/Generators/GeneratorsServiceProvider.php(28): Way\Generators\GeneratorsServiceProvider->package('way/generators')
#2 [internal function]: Way\Generators\GeneratorsServiceProvider->boot()
#3 /home/vagrant/Code/site/vendor/laravel/framework/src/Illuminate/Container/Container.php(523): call_user_func_array(Array, Array)
#4 /home/vagrant/Code/site/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(631): Illuminate\Container\Container->call(Array)
#5 /home/vagrant/Code/site/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(613): Illuminate\Foundation\Application->bootProvider(Object(Way\Generators\GeneratorsServiceProvider))
#6 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Way\Generators\GeneratorsServiceProvider), 20)
#7 /home/vagrant/Code/site/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(614): array_walk(Array, Object(Closure))
#8 /home/vagrant/Code/site/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(15): Illuminate\Foundation\Application->boot()
#9 /home/vagrant/Code/site/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(165): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#10 /home/vagrant/Code/site/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(192): Illuminate\Foundation\Application->bootstrapWith(Array)
#11 /home/vagrant/Code/site/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(89): Illuminate\Foundation\Console\Kernel->bootstrap()
#12 /home/vagrant/Code/site/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 {main}
```

**Comment by illuminate3** [comment]
This package is not L5 ready ... check the the rest of the issues here ... maybe somebody might have forked it to work with L5 ....

**Comment by skovmand** [comment]
I have this issue as well.

**Comment by JeffreyWay** [comment]
This is a L4 package.

Use https://github.com/laracasts/Laravel-5-Generators-Extended
